default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
#  socket: /tmp/mysql.sock

development:
  <<: *default
  database: cumplo_development

test:
  <<: *default
  database: cumplo_test

production:
  adapter: mysql2
  database: cumplo_production
  pool: 5
  username: root
  password:
  port: 3306



